### ISSUE TITLE
config.py

### ISSUE THREAD

**Issue by orenbenya** [sebastian-mora/aws_org_explorer#2]
looking at your awesome repo, and trying to implement it, I can't see how to continue with stage 2:
'add the connection details to config.py'
where is this file from ?

**Comment by shiftykey** [comment]
Agreed, some values can be inferred from the code. But having the file would be much easier.

**Comment by sebastian-mora** [comment]
Hi thanks for the feedback! I just added the file. Looks like I added to the .gitignore and never commit it to the repo.

**Comment by brendan-s1** [comment]
Got it working, thank you. Btw - unrelated - do you know of a good tool to export the graph to JS/HTML?

**Comment by sebastian-mora** [comment]
@brendan-s1 In the neo4j web browser there are some export options including image and data formats. I was originally looking into building a custom interface for the tool using NeoVis.js but the scope was expanding rapidly, so I decided to hold off for now. 

There is a list of vizualition tools on the neo4j website to check out https://neo4j.com/developer/tools-graph-visualization/
